# Generated by Django 3.2.9 on 2021-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.CharField(default='U', max_length=2),
        ),
    ]
